application:
    name: "Spring Boot Application"
server:
    port: 8888
spring:
    api-docs:
        path: /v3/api-docs
    swagger-ui:
        path: /swagger-ui.html
    packages-to-scan: com.bisoyi.helloapp.web.rest
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ${db_url:jdbc:postgresql://localhost:5432/your_db_name}
        username: ${db_user:root}
        password: ${db_pass:root}
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true
